
find_program(EDEPMANAGER depmanager)
if (${EDEPMANAGER} STREQUAL EDEPMANAGER-NOTFOUND)
    message(FATAL_ERROR "Dependency manager not found.")
else ()
    execute_process(COMMAND ${EDEPMANAGER} info cmakedir
            OUTPUT_VARIABLE depmanager_path)
    string(STRIP ${depmanager_path} depmanager_path)
    string(REPLACE "\\" "/" depmanager_path ${depmanager_path})
    list(PREPEND CMAKE_MODULE_PATH ${depmanager_path})
    include(DepManager)
endif ()

if (${${PRJPREFIX}_BUILD_SHARED})
    set(LOCAL_KIND shared)
else ()
    set(LOCAL_KIND static)
endif ()

dm_load_package(debugbreak)
dm_load_package(entt)
dm_load_package(magic_enum)
dm_load_package(stb_image)
dm_load_package(fmt KIND ${LOCAL_KIND})
dm_load_package(glad KIND ${LOCAL_KIND})
dm_load_package(glfw KIND ${LOCAL_KIND})
dm_load_package(glm KIND ${LOCAL_KIND})
dm_load_package(imgui KIND ${LOCAL_KIND})
dm_load_package(imguizmo KIND ${LOCAL_KIND})
dm_load_package(shaderc)
dm_load_package(spdlog KIND ${LOCAL_KIND})
dm_load_package(spirv-cross KIND ${LOCAL_KIND})
dm_load_package(yaml-cpp KIND ${LOCAL_KIND})
dm_load_package(nfd KIND ${LOCAL_KIND})
if (${${PRJPREFIX}_TESTING})
    message(STATUS "Loading GooglTest for the testing as ${LOCAL_KIND}.")
    dm_load_package(googletest KIND ${LOCAL_KIND})
endif ()

